import "dotenv/config";
import { eq } from "drizzle-orm";
import { db } from "./database";
import { productGenome } from "./schema";

const SELLER_ID = "seller_demo";

const rows = [
  {
    sellerId: SELLER_ID,
    sku: "KURTI-001",
    title: "Printed Cotton Kurti",
    brand: "NeoDemo",
    category: "Women > Kurtis",
    colour: "Blue",
    fabric: "Cotton",
    sizes: ["S", "M", "L", "XL"],
    weight: "0.30",
    hsnCode: "6204",
    costPrice: "250.00",
    sellingPrice: "699.00",
    images: [],
    attributes: { pattern: "Printed", occasion: "Casual", neckType: "Round Neck", sleeveLength: "Three-Quarter" },
  },
  {
    sellerId: SELLER_ID,
    sku: "KURTI-002",
    title: "Embroidered Rayon Kurti",
    brand: "NeoDemo",
    category: "Women > Kurtis",
    colour: "Green",
    fabric: "Rayon",
    sizes: ["S", "M", "L", "XL", "XXL"],
    weight: "0.32",
    hsnCode: "6204",
    costPrice: "310.00",
    sellingPrice: "849.00",
    images: [],
    attributes: { pattern: "Embroidered", occasion: "Festive", neckType: "Mandarin Collar", sleeveLength: "Full" },
  },
  {
    sellerId: SELLER_ID,
    sku: "KURTI-003",
    title: "Solid Silk Kurti",
    brand: "NeoDemo",
    category: "Women > Kurtis",
    colour: "Maroon",
    fabric: "Silk",
    sizes: ["M", "L", "XL"],
    weight: "0.35",
    hsnCode: "6204",
    costPrice: "420.00",
    sellingPrice: "1099.00",
    images: [],
    attributes: { pattern: "Solid", occasion: "Party", neckType: "V-Neck", sleeveLength: "Three-Quarter" },
  },
  {
    sellerId: SELLER_ID,
    sku: "SAREE-001",
    title: "Printed Silk Saree",
    brand: "NeoDemo",
    category: "Women > Sarees",
    colour: "Red",
    fabric: "Silk",
    sizes: ["Free Size"],
    weight: "0.60",
    hsnCode: "5007",
    costPrice: "700.00",
    sellingPrice: "1299.00",
    images: [],
    attributes: { pattern: "Printed", occasion: "Festive", blousePiece: true, sareeLength: "6.3m" },
  },
  {
    sellerId: SELLER_ID,
    sku: "SAREE-002",
    title: "Banarasi Cotton Saree",
    brand: "NeoDemo",
    category: "Women > Sarees",
    colour: "Yellow",
    fabric: "Cotton Silk",
    sizes: ["Free Size"],
    weight: "0.55",
    hsnCode: "5007",
    costPrice: "620.00",
    sellingPrice: "1199.00",
    images: [],
    attributes: { pattern: "Woven", occasion: "Wedding", blousePiece: true, sareeLength: "6.3m" },
  },
  {
    sellerId: SELLER_ID,
    sku: "TOP-001",
    title: "Casual Rayon Top",
    brand: "NeoDemo",
    category: "Women > Tops",
    colour: "Black",
    fabric: "Rayon",
    sizes: ["S", "M", "L", "XL"],
    weight: "0.20",
    hsnCode: "6206",
    costPrice: "180.00",
    sellingPrice: "599.00",
    images: [],
    attributes: { pattern: "Solid", occasion: "Casual", neckType: "Round Neck", sleeveLength: "Sleeveless" },
  },
  {
    sellerId: SELLER_ID,
    sku: "TOP-002",
    title: "Floral Georgette Top",
    brand: "NeoDemo",
    category: "Women > Tops",
    colour: "White",
    fabric: "Georgette",
    sizes: ["S", "M", "L"],
    weight: "0.18",
    hsnCode: "6206",
    costPrice: "220.00",
    sellingPrice: "699.00",
    images: [],
    attributes: { pattern: "Floral", occasion: "Casual", neckType: "V-Neck", sleeveLength: "Half" },
  },
  {
    sellerId: SELLER_ID,
    sku: "DRESS-001",
    title: "A-Line Cotton Dress",
    brand: "NeoDemo",
    category: "Women > Dresses",
    colour: "Pink",
    fabric: "Cotton",
    sizes: ["S", "M", "L", "XL"],
    weight: "0.28",
    hsnCode: "6204",
    costPrice: "350.00",
    sellingPrice: "899.00",
    images: [],
    attributes: { pattern: "Solid", occasion: "Casual", fit: "A-Line", sleeveLength: "Three-Quarter" },
  },
  {
    sellerId: SELLER_ID,
    sku: "LEGGING-001",
    title: "Ankle-Length Cotton Leggings",
    brand: "NeoDemo",
    category: "Women > Leggings",
    colour: "Black",
    fabric: "Cotton Lycra",
    sizes: ["S", "M", "L", "XL", "XXL"],
    weight: "0.15",
    hsnCode: "6115",
    costPrice: "120.00",
    sellingPrice: "349.00",
    images: [],
    attributes: { pattern: "Solid", fit: "Ankle Length" },
  },
  {
    sellerId: SELLER_ID,
    sku: "DUPATTA-001",
    title: "Chiffon Printed Dupatta",
    brand: "NeoDemo",
    category: "Women > Dupattas",
    colour: "Multicolor",
    fabric: "Chiffon",
    sizes: ["Free Size"],
    weight: "0.10",
    hsnCode: "5007",
    costPrice: "90.00",
    sellingPrice: "299.00",
    images: [],
    attributes: { pattern: "Printed", occasion: "Casual" },
  },
];

async function main() {
  // Idempotent: clear any prior demo seed for this seller before inserting fresh rows,
  // so re-running the seed doesn't accumulate duplicates.
  await db.delete(productGenome).where(eq(productGenome.sellerId, SELLER_ID));
  await db.insert(productGenome).values(rows);
  console.log(`Seeded ${rows.length} products`);
  process.exit(0);
}
main().catch((e) => {
  console.error(e);
  process.exit(1);
});
