CREATE TABLE "product_genome" (
	"id" serial PRIMARY KEY NOT NULL,
	"seller_id" varchar(100) NOT NULL,
	"sku" varchar(100) NOT NULL,
	"title" varchar(255),
	"brand" varchar(150),
	"category" varchar(150),
	"colour" varchar(100),
	"fabric" varchar(100),
	"sizes" jsonb,
	"weight" numeric(10, 2),
	"dimensions" jsonb,
	"hsn_code" varchar(50),
	"cost_price" numeric(10, 2),
	"selling_price" numeric(10, 2),
	"images" jsonb,
	"attributes" jsonb,
	"version" integer DEFAULT 1 NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_genome_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"product_id" integer NOT NULL,
	"seller_id" varchar(100) NOT NULL,
	"sku" varchar(100) NOT NULL,
	"title" varchar(255),
	"brand" varchar(150),
	"category" varchar(150),
	"colour" varchar(100),
	"fabric" varchar(100),
	"sizes" jsonb,
	"weight" numeric(10, 2),
	"dimensions" jsonb,
	"hsn_code" varchar(50),
	"cost_price" numeric(10, 2),
	"selling_price" numeric(10, 2),
	"images" jsonb,
	"attributes" jsonb,
	"version" integer NOT NULL,
	"archived_at" timestamp DEFAULT now() NOT NULL
);
